pipeline {
    agent any

    stages {
        stage('Build Backend') {
            steps {
                script {
                    git 'https://github.com/MELEK-WEB/devops-project.git'
                    dir('backend') {
                        sh 'docker-compose build backend'
                    }
                }
            }
        }
    }
}
